# Generated by Django 3.2.8 on 2021-10-15 22:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itemhub', '0001_initial'),
        ('clienthub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientItemRFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_number', models.CharField(max_length=100)),
                ('date_entered', models.DateField(auto_now_add=True)),
                ('date_received', models.DateField(default=datetime.datetime(2021, 10, 15, 22, 32, 19, 318299))),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_quoted', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clienthub.client')),
            ],
            options={
                'ordering': ['-date_received'],
            },
        ),
        migrations.CreateModel(
            name='RFQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemhub.productitem')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_items', to='rfqhub.clientitemrfq')),
            ],
        ),
    ]
