# Generated by Django 3.2.8 on 2021-10-19 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientitemrfq',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientitemrfq',
            name='is_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientitemrfq',
            name='date_received',
            field=models.DateField(default=datetime.datetime(2021, 10, 19, 0, 46, 27, 7701)),
        ),
    ]
