# Generated by Django 3.2.8 on 2021-11-16 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqhub', '0002_auto_20211019_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientitemrfq',
            name='date_received',
            field=models.DateField(default=datetime.datetime(2021, 11, 16, 18, 28, 35, 81219)),
        ),
    ]
