# Generated by Django 3.2.8 on 2021-10-15 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('aka', models.CharField(max_length=1024)),
                ('hazard', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materialhub.productmaterialcategory')),
            ],
            options={
                'verbose_name_plural': 'Materials',
                'db_table': 'productmaterial',
            },
        ),
    ]
