# Generated by Django 3.2.8 on 2021-10-15 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('part_number', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('brand', models.CharField(blank=True, max_length=150, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemhub.productitemcategory')),
            ],
            options={
                'verbose_name_plural': 'Items',
                'db_table': 'productitem',
            },
        ),
    ]
